---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Discover and Learn
logo: /assets/images/logo.png # You can add own logo
description: Discover and Learn about ARCHER2 and supercomputers # Add your awesome description
copyright: Copyright 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: Topics
    submenu:
     - name: Hardware
       url: /category/hardware/
     - name: Activities
       url: /category/activities/
     - name: ARCHER2 EPCC outreach online interactive site
       url: https://outreach.epcc.ed.ac.uk/
  - name: About
    url: /about/
    submenu:
     - name: EPCC Discover and Learn
       url: /about/
     - name: EPCC
       url: https://www.epcc.ed.ac.uk/
     - name: ARCHER2
       url: https://www.archer2.ac.uk
  - name: Contact
    url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.


excerpt_separator: <!--more-->

#-------------------------------
# Hero Section
hero:
  hero-subtitle: I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print.
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: EPCC and ARCHER2 Outreach team

#-------------------------------
# Contact Info
contact:
  email: l.smith@epcc.ed.ac.uk
  phone: +44 (0)131 650 5030
  address:
    city: Edinburgh
    street: Bayes Centre, 47 Potterrow, Edinburgh EH8 9BT

# Contact Form
contact-form: l.smith@epcc.ed.ac.uk

# Social links
social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-twitter-alt", link: "#" }
  - { icon: "ti-linkedin", link: "#" }
  - { icon: "ti-github", link: "#" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
